create table "waitline" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "guest_name" TEXT NOT NULL,
  "phone_number" VARCHAR not NULL,
  "size" INTEGER not NULL,
  "user_id" INTEGER REFERENCES "users"(id) ON DELETE CASCADE NOT NULL
)